### ISSUE TITLE
Exercises 18-2 thru 18-4

### ISSUE THREAD

**Issue by smattingly** [csci320/brosekerg#20]
Your responses to these exercises don't show the commands called for in the instructions.

**Comment by brosekerg** [comment]
18-2 says to backup learning center which i did (backup.sql) which i did through mysql dump. then i dropped a table, and truncated a table, and then restored the backup so nothing was deleted. What did i miss with the instructions?

18-3 i made a backup learning center named nlc_backup and it has the same contents as learning_center, meaning i restored it, so what am i missing on this exercise?

18-4 i dropped a atable and truncated a table and when i did the rollback the changes did not get revoked, showing that you cant rollback dropped or truncated tables, as you told us in the instructions for 18-4 exercise.

I will need more clarity in what i got wrog because when i just reviewed these 3 exercises i didn't see where i got anything wrong

**Comment by smattingly** [comment]
I want to see all the commands. For example, 18-2 asks you to do the four things you list above: backup, drop, truncate, restore. You did not show me the first or the fourth (which are the entire point of the question.) Similar comments apply to the other exercises. Note that some of these steps are bash terminal commands, so they won't be captured by `tee` in the mysql client. It is okay to copy the bash commands and paste them into a file.

**Comment by brosekerg** [comment]
yeah that was my problem because when i exited mysql i lost my commands, i will make this right

**Comment by brosekerg** [comment]
gitpod /workspace/brosekerg $ mysqldump learning_center > backup.sql

**Comment by brosekerg** [comment]
done

**Comment by smattingly** [comment]
18-3 is ok. 18-2 and 18-4 still don't show what the exercise asks for.

**Comment by brosekerg** [comment]
18-2 should show what youre asking for what am i missing? i have the back up and restore commands in there this time and 18-4 i updated as well and showed you i was using the throwaway copy of the database, so i may need further instructions on this one to me it appears i have everything

**Comment by smattingly** [comment]
18-2. It would be good to have a demonstration that the backup command put things back. But the big problem, I thought, was that you had not shown the dropping of a table. I see now that you did; the error messages caused me to miss it. This one is okay.

18-4. The instructions say to start a transaction. Your file does not show that. I am not going to continue pointing out details like that to you when you simply haven't followed the instructions.

**Comment by brosekerg** [comment]
this one is updated as well let me know if 18-4 is correct now

**Comment by smattingly** [comment]
👍
