### ISSUE TITLE
Exercise 25-1

### ISSUE THREAD

**Issue by smattingly** [csci320/brosekerg#23]
https://github.com/csci320/brosekerg/blob/9c778f2f87fa119fbd911151d8a3306542ff0ec3/Exercise%20Set%2025#L5

As discussed in class, `memory` values should be numbers, not strings. This will mess up query results until it's fixed.

**Comment by brosekerg** [comment]
okay that makes sense thank you

**Comment by brosekerg** [comment]
this is fixed with the correct results

**Comment by smattingly** [comment]
https://github.com/csci320/brosekerg/blob/6d5b39e80346f4783f2b373326a964f9cd5d935d/Exercise%20Set%2025#L96-L104

This is still not correct.

**Comment by brosekerg** [comment]
> db.computers.count(
{memory: { $lt: 8 }})
3 

sorry the comment where you told me to use the count method was on a different post, didnt realize this one was this simple

**Comment by smattingly** [comment]
👍
